title: Gustavo Flores
description: Personal Website
author: Gustavo Flores
email: gustavoflor3s@gmail.com
baseurl: ""
url: "https://www.gusman.com"
theme: minima
markdown: kramdown
permalink: /:year/:month/:day/:title.html
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
include:
  - .htaccess
